# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kersul/Develop/Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kersul/Develop/Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kersul/Develop/Compiler/CMakeFiles /Users/kersul/Develop/Compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kersul/Develop/Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CompilerTests

# Build rule for target.
CompilerTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CompilerTests
.PHONY : CompilerTests

# fast build rule for target.
CompilerTests/fast:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/build
.PHONY : CompilerTests/fast

#=============================================================================
# Target rules for targets named Compiler

# Build rule for target.
Compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Compiler
.PHONY : Compiler

# fast build rule for target.
Compiler/fast:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/build
.PHONY : Compiler/fast

src/lexical-transitions.o: src/lexical-transitions.c.o

.PHONY : src/lexical-transitions.o

# target to build an object file
src/lexical-transitions.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical-transitions.c.o
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical-transitions.c.o
.PHONY : src/lexical-transitions.c.o

src/lexical-transitions.i: src/lexical-transitions.c.i

.PHONY : src/lexical-transitions.i

# target to preprocess a source file
src/lexical-transitions.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical-transitions.c.i
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical-transitions.c.i
.PHONY : src/lexical-transitions.c.i

src/lexical-transitions.s: src/lexical-transitions.c.s

.PHONY : src/lexical-transitions.s

# target to generate assembly for a file
src/lexical-transitions.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical-transitions.c.s
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical-transitions.c.s
.PHONY : src/lexical-transitions.c.s

src/lexical.o: src/lexical.c.o

.PHONY : src/lexical.o

# target to build an object file
src/lexical.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical.c.o
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical.c.o
.PHONY : src/lexical.c.o

src/lexical.i: src/lexical.c.i

.PHONY : src/lexical.i

# target to preprocess a source file
src/lexical.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical.c.i
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical.c.i
.PHONY : src/lexical.c.i

src/lexical.s: src/lexical.c.s

.PHONY : src/lexical.s

# target to generate assembly for a file
src/lexical.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/lexical.c.s
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/lexical.c.s
.PHONY : src/lexical.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.c.s
.PHONY : src/main.c.s

src/semantic.o: src/semantic.c.o

.PHONY : src/semantic.o

# target to build an object file
src/semantic.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/semantic.c.o
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/semantic.c.o
.PHONY : src/semantic.c.o

src/semantic.i: src/semantic.c.i

.PHONY : src/semantic.i

# target to preprocess a source file
src/semantic.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/semantic.c.i
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/semantic.c.i
.PHONY : src/semantic.c.i

src/semantic.s: src/semantic.c.s

.PHONY : src/semantic.s

# target to generate assembly for a file
src/semantic.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/semantic.c.s
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/semantic.c.s
.PHONY : src/semantic.c.s

src/text-manipulator.o: src/text-manipulator.c.o

.PHONY : src/text-manipulator.o

# target to build an object file
src/text-manipulator.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/text-manipulator.c.o
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/text-manipulator.c.o
.PHONY : src/text-manipulator.c.o

src/text-manipulator.i: src/text-manipulator.c.i

.PHONY : src/text-manipulator.i

# target to preprocess a source file
src/text-manipulator.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/text-manipulator.c.i
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/text-manipulator.c.i
.PHONY : src/text-manipulator.c.i

src/text-manipulator.s: src/text-manipulator.c.s

.PHONY : src/text-manipulator.s

# target to generate assembly for a file
src/text-manipulator.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/src/text-manipulator.c.s
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/text-manipulator.c.s
.PHONY : src/text-manipulator.c.s

tests/lexical-transitions.tests.o: tests/lexical-transitions.tests.c.o

.PHONY : tests/lexical-transitions.tests.o

# target to build an object file
tests/lexical-transitions.tests.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical-transitions.tests.c.o
.PHONY : tests/lexical-transitions.tests.c.o

tests/lexical-transitions.tests.i: tests/lexical-transitions.tests.c.i

.PHONY : tests/lexical-transitions.tests.i

# target to preprocess a source file
tests/lexical-transitions.tests.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical-transitions.tests.c.i
.PHONY : tests/lexical-transitions.tests.c.i

tests/lexical-transitions.tests.s: tests/lexical-transitions.tests.c.s

.PHONY : tests/lexical-transitions.tests.s

# target to generate assembly for a file
tests/lexical-transitions.tests.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical-transitions.tests.c.s
.PHONY : tests/lexical-transitions.tests.c.s

tests/lexical.tests.o: tests/lexical.tests.c.o

.PHONY : tests/lexical.tests.o

# target to build an object file
tests/lexical.tests.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical.tests.c.o
.PHONY : tests/lexical.tests.c.o

tests/lexical.tests.i: tests/lexical.tests.c.i

.PHONY : tests/lexical.tests.i

# target to preprocess a source file
tests/lexical.tests.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical.tests.c.i
.PHONY : tests/lexical.tests.c.i

tests/lexical.tests.s: tests/lexical.tests.c.s

.PHONY : tests/lexical.tests.s

# target to generate assembly for a file
tests/lexical.tests.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/lexical.tests.c.s
.PHONY : tests/lexical.tests.c.s

tests/text-manipulator.tests.o: tests/text-manipulator.tests.c.o

.PHONY : tests/text-manipulator.tests.o

# target to build an object file
tests/text-manipulator.tests.c.o:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/text-manipulator.tests.c.o
.PHONY : tests/text-manipulator.tests.c.o

tests/text-manipulator.tests.i: tests/text-manipulator.tests.c.i

.PHONY : tests/text-manipulator.tests.i

# target to preprocess a source file
tests/text-manipulator.tests.c.i:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/text-manipulator.tests.c.i
.PHONY : tests/text-manipulator.tests.c.i

tests/text-manipulator.tests.s: tests/text-manipulator.tests.c.s

.PHONY : tests/text-manipulator.tests.s

# target to generate assembly for a file
tests/text-manipulator.tests.c.s:
	$(MAKE) -f CMakeFiles/CompilerTests.dir/build.make CMakeFiles/CompilerTests.dir/tests/text-manipulator.tests.c.s
.PHONY : tests/text-manipulator.tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CompilerTests"
	@echo "... Compiler"
	@echo "... src/lexical-transitions.o"
	@echo "... src/lexical-transitions.i"
	@echo "... src/lexical-transitions.s"
	@echo "... src/lexical.o"
	@echo "... src/lexical.i"
	@echo "... src/lexical.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/semantic.o"
	@echo "... src/semantic.i"
	@echo "... src/semantic.s"
	@echo "... src/text-manipulator.o"
	@echo "... src/text-manipulator.i"
	@echo "... src/text-manipulator.s"
	@echo "... tests/lexical-transitions.tests.o"
	@echo "... tests/lexical-transitions.tests.i"
	@echo "... tests/lexical-transitions.tests.s"
	@echo "... tests/lexical.tests.o"
	@echo "... tests/lexical.tests.i"
	@echo "... tests/lexical.tests.s"
	@echo "... tests/text-manipulator.tests.o"
	@echo "... tests/text-manipulator.tests.i"
	@echo "... tests/text-manipulator.tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

